//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qlkdstDB.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class datcoc
    {
        public decimal iddatcoc { get; set; }
        public Nullable<System.DateTime> ngaydatcoc { get; set; }
        public Nullable<decimal> idtour { get; set; }
        public string sobiennhan { get; set; }
        public string nguoilambn { get; set; }
        public string daily { get; set; }
        public string tenkhach { get; set; }
        public string diachi { get; set; }
        public string dienthoai { get; set; }
        public string noidung { get; set; }
        public Nullable<decimal> sotien { get; set; }
        public Nullable<System.DateTime> ngaytao { get; set; }
        public string nguoitao { get; set; }
        public Nullable<System.DateTime> ngaysua { get; set; }
        public string nguoisua { get; set; }
        public string hinhthucthanhtoan { get; set; }
        public string chungtugoc { get; set; }
        public string tenmay { get; set; }
        public string loaitien { get; set; }
        public Nullable<decimal> tygia { get; set; }
    }
}
