//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qlkdstDB.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class dmhoahong
    {
        public int idhoahong { get; set; }
        public Nullable<decimal> idtour { get; set; }
        public string sales { get; set; }
        public Nullable<decimal> id_dsk { get; set; }
        public string tenkhach { get; set; }
        public string socmnd { get; set; }
        public Nullable<decimal> sotien { get; set; }
        public string salesnm { get; set; }
    }
}
