//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qlkdstDB.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class dmkhachhang
    {
        public string makh { get; set; }
        public string codecn { get; set; }
        public string tengiaodich { get; set; }
        public string tenthuongmai { get; set; }
        public string diachi { get; set; }
        public string thanhpho { get; set; }
        public string quocgia { get; set; }
        public string telephone { get; set; }
        public string tax { get; set; }
        public string fax { get; set; }
        public string email { get; set; }
        public string nguoiqh { get; set; }
        public Nullable<System.DateTime> ngaytao { get; set; }
        public string nguoitao { get; set; }
        public Nullable<System.DateTime> ngaysua { get; set; }
        public string nguoisua { get; set; }
        public string ghichukhigiaodich { get; set; }
        public string lsthamgiatour { get; set; }
        public string nganhnghe { get; set; }
        public string chinhanh { get; set; }
    }
}
