//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qlkdstDB.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class mainmenu
    {
        public int areaid { get; set; }
        public string areaname { get; set; }
        public Nullable<bool> show_mk { get; set; }
        public string areacss { get; set; }
        public Nullable<int> thutu { get; set; }
    }
}
