//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qlkdstDB.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tourlog
    {
        public decimal idtourlog { get; set; }
        public decimal idtour { get; set; }
        public string sgtcode { get; set; }
        public string chudetour { get; set; }
        public Nullable<System.DateTime> ngaytao { get; set; }
        public string nguoitao { get; set; }
        public Nullable<System.DateTime> batdau { get; set; }
        public Nullable<System.DateTime> ketthuc { get; set; }
        public string tuyentq { get; set; }
        public string diemtq { get; set; }
        public Nullable<int> sokhachdk { get; set; }
        public Nullable<decimal> doanhthudk { get; set; }
        public string makh { get; set; }
        public string tenkh { get; set; }
        public string diachi { get; set; }
        public string dienthoai { get; set; }
        public string fax { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> ngaydamphan { get; set; }
        public string hinhthucgiaodich { get; set; }
        public Nullable<System.DateTime> ngaykyhopdong { get; set; }
        public string nguoikyhopdong { get; set; }
        public Nullable<System.DateTime> hanxuatvmb { get; set; }
        public Nullable<System.DateTime> ngaythanhlyhd { get; set; }
        public Nullable<int> sokhachtt { get; set; }
        public Nullable<decimal> doanhthutt { get; set; }
        public string chuongtrinhtour { get; set; }
        public string noidungthanhlyhd { get; set; }
        public string dichvu { get; set; }
        public string daily { get; set; }
        public string loaitourid { get; set; }
        public string trangthai { get; set; }
        public Nullable<System.DateTime> ngaysua { get; set; }
        public string nguoisua { get; set; }
        public string chinhanh { get; set; }
        public Nullable<System.DateTime> ngaynhandutien { get; set; }
        public string lidonhandu { get; set; }
        public string sohopdong { get; set; }
        public Nullable<decimal> laichuave { get; set; }
        public Nullable<decimal> laigomve { get; set; }
        public Nullable<decimal> laithuctegomve { get; set; }
        public string nguyennhanhuythau { get; set; }
        public string nguontour { get; set; }
        public string filekhachditour { get; set; }
        public string filevemaybay { get; set; }
        public string filebiennhan { get; set; }
        public string nguoidaidien { get; set; }
        public string doitacnuocngoai { get; set; }
        public Nullable<System.DateTime> ngayhuytour { get; set; }
        public string nguoithaotac { get; set; }
        public string hanhdong { get; set; }
        public Nullable<System.DateTime> thoigianthaotac { get; set; }
    }
}
