//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qlkdstDB.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class vemaybay
    {
        public decimal id_vmb { get; set; }
        public Nullable<decimal> idtour { get; set; }
        public string chuyenbay { get; set; }
        public Nullable<System.DateTime> ngaybay { get; set; }
        public string diemdi { get; set; }
        public string diemden { get; set; }
        public string giodi { get; set; }
        public string gioden { get; set; }
        public string nguoitao { get; set; }
        public Nullable<System.DateTime> ngaytao { get; set; }
        public string nguoisua { get; set; }
        public Nullable<System.DateTime> ngaysua { get; set; }
        public Nullable<int> sove_adl_d { get; set; }
        public Nullable<int> sove_chl_d { get; set; }
        public Nullable<int> sove_inf_d { get; set; }
        public Nullable<int> sove_adl_v { get; set; }
        public Nullable<int> sove_chl_v { get; set; }
        public Nullable<int> sove_inf_v { get; set; }
        public string luotdive { get; set; }
    }
}
