//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qlkdstDB.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class vie_quyenusrtheocn
    {
        public int Id { get; set; }
        public string chinhanh { get; set; }
        public string tencn { get; set; }
        public string diachi { get; set; }
        public string thanhpho { get; set; }
        public string dienthoai { get; set; }
        public string fax { get; set; }
        public string masothue { get; set; }
        public bool trangthai { get; set; }
        public Nullable<System.DateTime> ngaytao { get; set; }
        public string nguoitao { get; set; }
        public Nullable<System.DateTime> ngaysua { get; set; }
        public string nguoisua { get; set; }
        public Nullable<int> idkhucn { get; set; }
        public string tenkhucn { get; set; }
        public string userId { get; set; }
        public string username { get; set; }
    }
}
