//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qlkdstDB.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class vie_khachNotInRoominglist
    {
        public decimal id_dsk { get; set; }
        public Nullable<decimal> idtour { get; set; }
        public string tenkhach { get; set; }
        public string hochieu { get; set; }
        public Nullable<System.DateTime> hieuluchochieu { get; set; }
        public Nullable<System.DateTime> ngaysinh { get; set; }
        public string socmnd { get; set; }
        public Nullable<System.DateTime> ngaycmnd { get; set; }
        public string noicapcmnd { get; set; }
        public string phai { get; set; }
        public string dienthoai { get; set; }
        public string quoctich { get; set; }
        public bool trangthai { get; set; }
    }
}
