//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qlkdstDB.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class vie_dsmenu
    {
        public int menuid { get; set; }
        public string menunm { get; set; }
        public string menulink { get; set; }
        public Nullable<int> areaid { get; set; }
        public bool show_mk { get; set; }
        public string classcss { get; set; }
        public string role { get; set; }
        public string actionnm { get; set; }
        public string controllernm { get; set; }
        public string areamvc { get; set; }
        public Nullable<int> thutu { get; set; }
        public string areaname { get; set; }
        public string areacss { get; set; }
        public Nullable<int> tt { get; set; }
        public string nguoitao { get; set; }
        public Nullable<System.DateTime> ngaytao { get; set; }
        public string nguoisua { get; set; }
        public Nullable<System.DateTime> ngaysua { get; set; }
        public string userId { get; set; }
        public string username { get; set; }
    }
}
